### ISSUE TITLE
考虑支持windows吗！

### ISSUE THREAD

**Issue by yanhaijing** [phodal/ebook-boilerplate#2]

**Comment by phodal** [comment]
哈哈，遇到什么问题了？

**Comment by yanhaijing** [comment]
make missing

**Comment by phodal** [comment]
那就装一个 ``make``，``cygwin`` 或者 ``chocolatey`` 来安装一个

**Comment by yanhaijing** [comment]
拆分为多个 .sh 就能解决了

**Comment by BrainBee** [comment]
在Windows 10 环境下编译出现  
“! Package inputenc Error: Unicode char 前 (U+524D)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.160 \#前
           言 
”
TEX 发行版是：TEX Live2017
pandoc版本是：
$ pandoc --version
pandoc.exe 2.0.5
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.5
编译环境： MINGW64
使用的编辑器，notepad++，使用UTF-8编码。

**Comment by yanhaijing** [comment]
https://github.com/yanhaijing/gitbook-boilerplate
一个基于gitbook快速写电子书的模版，支持html、pdf、**docx**、epub、mobi
@BrainBee 这个兼容windows，用node做的兼容

**Comment by BrainBee** [comment]
@yanhaijing ，谢谢！

**Comment by yanhaijing** [comment]
@BrainBee 欢迎试用，✧(≖ ◡ ≖✿)嘿嘿
